server:
  port: 8080

spring:
  application:
    name:
      file-storage-service

  datasource:
    url: jdbc:postgresql://postgres_storage:5432/file-storage
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/