server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/file-storage
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    url: /v3/api-docs/swagger-config
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs